# name-template: 'v$RESOLVED_VERSION 🌈'
# tag-template: 'v$RESOLVED_VERSION'
include-paths:
  - "came_domotic_unofficial/"
autolabeler:
  - label: 'chore'
    files:
      - '*.md'
      - 'pyproject.toml'
    branch:
      - '/docs{0,1}\/.+/'
      - '/actions{0,1}\/.+/'
  - label: 'fix'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'feature'
    branch:
      - '/feature\/.+/'
categories:
  - title: 'Features'
    labels:
      - 'feature'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
  - title: 'Maintenance'
    label: 'chore'
# change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
# change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
# version-resolver:
#   major:
#     labels:
#       - 'major'
#   minor:
#     labels:
#       - 'minor'
#   patch:
#     labels:
#       - 'patch'
#   default: patch
template: |
  ## Changelog

  $CHANGES
footer: |
  $REPOSITORY