# Copyright 2024 - GitHub user: fredericks1982

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License. 

# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build to TestPyPI and run unit tests 

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run the tests'
        required: true
        type: choice
        options:
          - testpypi
          # - pypi
        default: 'testpypi'
      version:
        description: 'Package version to build and publish to TestPyPI'
        required: true
        type: string
        default: '1.0.0rc1'


permissions:
  contents: read

jobs:
  build_and_publish_testpypi:
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
    
    - name: Check out code with history
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install all dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Set package version
      run: |
        export SETUPTOOLS_SCM_PRETEND_VERSION=${{ github.event.inputs.version }}

    - name: Build package
      run: python -m build

    - name: Check package
      run: python -m twine check dist/*

    - name: Publish to (Test)PyPI
      uses: pypa/gh-action-pypi-publish@e53eb8b103ffcb59469888563dc324e3c8ba6f06 # v1.8.12
      with:
        repository-url: https://test.pypi.org/legacy/
        skip-existing: true
