# Copyright 2024 - GitHub user: fredericks1982

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License. 

# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build to TestPyPI and run unit tests 

on:
  create:
    tags:
      - 'v*.*'
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_and_publish_testpypi:
    environment: testpypi
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
    - name: Check out code with history
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: "3.x"
    - name: Install all dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Publish to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        # skip-existing: true

  test:
    needs: build_and_publish_testpypi
    environment: testpypi
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: "3.x"
    - name: Install all dependencies
      run: |
        python -m pip install --upgrade pip
        pip install hypothesis pytest pytest-cov requests 
    - name: Install came_domotic_unofficial from TEST PyPI repository
      run: |
        pip install --index-url https://test.pypi.org/simple/ "came_domotic_unofficial-fredericks1982"
    - name: Test with pytest
      run: |
        pytest --cov
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      