name: 'Repository maintenance scheduled tasks'

on:
  schedule:
    - cron: '33 7 * * *'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write
  discussions: write

concurrency:
  group: project-maintenance-jobs

jobs:
  lock-inactive-threads:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v5
        with:
            issue-inactive-days: '90'
            pr-inactive-days: '90'
            discussion-inactive-days: '90'
            add-issue-labels: 'locked'
            add-pr-labels: 'locked'
            add-discussion-labels: 'locked'
            issue-comment: >
                This item has been automatically locked due to inactivity.
                Please unlock this thread if you have further questions or comments.
            pr-comment: >
                This item has been automatically locked due to inactivity.
                Please unlock this thread if you have further questions or comments.
            discussion-comment: >
                This item has been automatically locked due to inactivity.
                Please unlock this thread if you have further questions or comments.
            log-output: true
            
